function PolarMIMOGenerator(n, K, R, qamSize, qamTab, precode, H)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Simulate polar coding of bits in MIMO systems.
% Optionally can apply SVD precoding based on known channel matrix
%
% Inputs:
%   n - number of antennas.
%   K - number of bits per symbol per antenna
%   R - polar coding rate
%       e.g. K=16, R=.5 -> 32 bits output of polar codes
%   qamSize - Size of QAM constellation to be transnmitted in each antenna.
%             2 corresponds to {+-1}, 4 corresponds to {+-1, +-i},...
%   qamTab - the table generated by ConstellationTable.m
%   precode - a binary flag for SVD precoding
%   H - the known channel, if available, used for precoding
%
%   Output - MIMO signal about to be transmitted
%
%   Example: PolarMIMOGenerator(4,4,1,1,1,ones(4))
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

LEN = 20;

% Create constallation table
qamTable = qamTab.table;

data = zeros(n, K, LEN); % antennas, bits, nMessages
enc = zeros(n, nextpow2(K/R), LEN); %antennas, polarized bits, nMessages

if (precode)
    [U,D,V] = svd(H);
end


for (kk = 1 : LEN)
    data(:,:,kk) = randi([0, 1], n, K); %generate bits
    for (i = 1 : n)
        enc(i,:,kk) = nrPolarEncode(data(i,:,kk), K/R);	
    end

end

enc = reshape(enc, n, LEN*nextpow2(K/R)/qamSize, qamSize);

collapsed = bi2de(enc);

output = qamTable(collapsed);

if (precode)
    output = V.*output;
end

end

